// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmnPA9GP31ELTJQMg9qeHjn1n_W9xvxk4',
    appId: '1:465048864139:web:96bcd7fa5bf5a840a91b8e',
    messagingSenderId: '465048864139',
    projectId: 'gearbeat-mvp',
    authDomain: 'gearbeat-mvp.firebaseapp.com',
    databaseURL: 'https://gearbeat-mvp-default-rtdb.firebaseio.com',
    storageBucket: 'gearbeat-mvp.firebasestorage.app',
    measurementId: 'G-3211LT54M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_GrmS6yuLEovRoS1S1JGMk7-poqGDnFo',
    appId: '1:465048864139:android:646b201d0716688aa91b8e',
    messagingSenderId: '465048864139',
    projectId: 'gearbeat-mvp',
    databaseURL: 'https://gearbeat-mvp-default-rtdb.firebaseio.com',
    storageBucket: 'gearbeat-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDab7LVynz5oLQl5CUdqvWOTf2InAAYOPI',
    appId: '1:465048864139:ios:84304d90bd357450a91b8e',
    messagingSenderId: '465048864139',
    projectId: 'gearbeat-mvp',
    databaseURL: 'https://gearbeat-mvp-default-rtdb.firebaseio.com',
    storageBucket: 'gearbeat-mvp.firebasestorage.app',
    iosBundleId: 'com.example.appPreserieDj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDab7LVynz5oLQl5CUdqvWOTf2InAAYOPI',
    appId: '1:465048864139:ios:84304d90bd357450a91b8e',
    messagingSenderId: '465048864139',
    projectId: 'gearbeat-mvp',
    databaseURL: 'https://gearbeat-mvp-default-rtdb.firebaseio.com',
    storageBucket: 'gearbeat-mvp.firebasestorage.app',
    iosBundleId: 'com.example.appPreserieDj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmnPA9GP31ELTJQMg9qeHjn1n_W9xvxk4',
    appId: '1:465048864139:web:c03def9509ca3efda91b8e',
    messagingSenderId: '465048864139',
    projectId: 'gearbeat-mvp',
    authDomain: 'gearbeat-mvp.firebaseapp.com',
    databaseURL: 'https://gearbeat-mvp-default-rtdb.firebaseio.com',
    storageBucket: 'gearbeat-mvp.firebasestorage.app',
    measurementId: 'G-CLT5XBS8VK',
  );
}
